{
 "title": "ProKI-Chair1-smallmachine",
 "time": { "from": "now-5s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    CASE \n        WHEN EXISTS (\n            SELECT 1\n            FROM smallmachine \n            WHERE \"time\" >= TIMESTAMP $__timeFrom() + INTERVAL '2 hours' AND \"time\" < TIMESTAMP $__timeTo() + INTERVAL '2 hours'\n        ) \n        THEN 'Ok' \n        ELSE 'Not Ok' \n    END AS status;"
    }
   ]
  },
  {
   "title": "Events Per Second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 7, "y": 8 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  public.time_bucket('1 second'::INTERVAL, \"time\" - INTERVAL '2 hours') AS bucket,\n  COUNT(*) AS Events\nFROM chair1.smallmachine\nWHERE \"time\" >= TIMESTAMP $__timeFrom() + INTERVAL '2 hours' AND \"time\" < TIMESTAMP $__timeTo() + INTERVAL '2 hours'\nGROUP BY bucket\nORDER BY bucket DESC;"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 12, "x": 7, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT \"time\" - INTERVAL '2 hours' as \"time\", x, y\nFROM chair1.smallmachine\nWHERE\n\t\"time\" > TIMESTAMP $__timeFrom() + INTERVAL '2 hours' AND\n\t\"time\" < TIMESTAMP $__timeTo() + INTERVAL '2 hours'\nORDER BY \"time\" DESC\nLIMIT 50000"
    }
   ]
  }
 ]
}